// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// 
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARXcXxBMz7oLcNwsaoklwtXocC3lEvr_Y',
    appId: '1:138355639139:web:3cfb8ed30785b8a6abc956',
    messagingSenderId: '138355639139',
    projectId: 'moviles-app-2024-itc',
    authDomain: 'moviles-app-2024-itc.firebaseapp.com',
    storageBucket: 'moviles-app-2024-itc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFTIEPgXjjysH90u6wxHwZNQiQ61mpyas',
    appId: '1:138355639139:android:69eef5230ba80a82abc956',
    messagingSenderId: '138355639139',
    projectId: 'moviles-app-2024-itc',
    storageBucket: 'moviles-app-2024-itc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEa6_2xzReb7_xIM0nSk393IP5ldXsGko',
    appId: '1:138355639139:ios:39522d3d9a1843ddabc956',
    messagingSenderId: '138355639139',
    projectId: 'moviles-app-2024-itc',
    storageBucket: 'moviles-app-2024-itc.appspot.com',
    iosBundleId: 'com.example.mainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEa6_2xzReb7_xIM0nSk393IP5ldXsGko',
    appId: '1:138355639139:ios:39522d3d9a1843ddabc956',
    messagingSenderId: '138355639139',
    projectId: 'moviles-app-2024-itc',
    storageBucket: 'moviles-app-2024-itc.appspot.com',
    iosBundleId: 'com.example.mainApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARXcXxBMz7oLcNwsaoklwtXocC3lEvr_Y',
    appId: '1:138355639139:web:a6e7c8e502af7986abc956',
    messagingSenderId: '138355639139',
    projectId: 'moviles-app-2024-itc',
    authDomain: 'moviles-app-2024-itc.firebaseapp.com',
    storageBucket: 'moviles-app-2024-itc.appspot.com',
  );
}
